### ISSUE TITLE
Installation issues, failed to import "typescript" and Qwik Component was not invoked correctly

### ISSUE THREAD

**Issue by apiel** [QwikDev/astro#45]
After cloning the tutorial from Astro https://github.com/withastro/blog-tutorial-demo
I followed the installation instruction for setting up Qwik, I first got the following issue:

`[vite] Error when evaluating SSR module /node_modules/@qwikdev/astro/src/index.ts: failed to import "typescript"`

After running `npm install typescript --save-dev` problem was solved.

However, now there is a new issue:

`Internal assert, this is likely caused by a bug in Qwik: The Qwik Component was not invoked correctly`

**Comment by thejackshelton** [comment]
Hey @apiel! 

Not sure why it does not install typescript by default 🤔 . Maybe we need it as a peer dependency? I will try to reproduce this.

> Internal assert, this is likely caused by a bug in Qwik: The Qwik Component was not invoked correctly

Yeah so currently trying to solve this right now. The problem is because there is multiple JSX frameworks. That template uses Preact for example, and Astro currently needs an `include` or `exclude` option in the astro config. 
https://github.com/QwikDev/astro/issues/13#issuecomment-1815445681

**Comment by apiel** [comment]
thanks

**Comment by thejackshelton** [comment]
Hey @apiel, it should now work out of the box with preact!

If you run into any problems, make sure to put qwik at the beginning of the integrations array.
